### See status
GET http://localhost:8004/status

### Get output
GET http://localhost:8004/get_plan?IDs=1234

### Send input data as JSON
POST http://localhost:8004//mission_request
Content-Type: application/json

{
  "id": 1234,
  "name": "no mission",
  "settings": [
    {
      "devices": {
        "deviceId": "0",
        "category": "dji_M210_noetic",
        "speed_mission": 7,
        "speed_navegation": 15
      },
      "mission": {
        "height": 10,
        "offset": 10,
        "tower": 10
      }
    },
    {
      "devices": {
        "deviceId": "1",
        "category": "dji_M210_noetic",
        "speed_mission": 7,
        "speed_navegation": 15
      },
      "mission": {
        "height": 10,
        "offset": 10,
        "tower": 10
      }
    },
    {
      "devices": {
        "deviceId": "2",
        "category": "dji_M210_noetic",
        "speed_mission": 7,
        "speed_navegation": 15
      },
      "mission": {
        "height": 10,
        "offset": 10,
        "tower": 10
      }
    },
    {
      "devices": {
        "deviceId": "3",
        "category": "dji_M210_noetic",
        "speed_mission": 7,
        "speed_navegation": 15
      },
      "mission": {
        "height": 10,
        "offset": 10,
        "tower": 10
      }
    }
  ],
  "objetivo": 0,
  "bases": [
    {
      "latitude": 38.1385113182596,
      "longitude": -3.176305522392061
    },
    {
      "latitude": 38.13749084416372,
      "longitude": -3.1805328708085483
    },
    {
      "latitude": 38.13410070943499,
      "longitude": -3.1754686621366375
    },
    {
      "latitude": 38.136321847002336,
      "longitude": -3.1697317913580036
    }
  ],
  "meteo": [],
  "loc": [
    {
      "name": "Elements",
      "items": [
        {
          "latitude": 38.13966793639006,
          "longitude": -3.168728594889372
        },
        {
          "latitude": 38.13996830736248,
          "longitude": -3.16762589340327
        },
        {
          "latitude": 38.1402766196862,
          "longitude": -3.166505577905428
        },
        {
          "latitude": 38.14062040853257,
          "longitude": -3.165611516354345
        }
      ]
    },
    {
      "name": "Elements",
      "items": [
        {
          "latitude": 38.13601387107713,
          "longitude": -3.17853735196563
        },
        {
          "latitude": 38.13611084052413,
          "longitude": -3.176610125243361
        },
        {
          "latitude": 38.13624534697013,
          "longitude": -3.174186980324723
        },
        {
          "latitude": 38.13527642840854,
          "longitude": -3.172451298169662
        }
      ]
    }
  ]
}