### Start Compute
GET http://localhost:8004/mission_request

### See status
GET http://localhost:8004/status

### Get output
GET http://localhost:8004/output

### Send bases as JSON
POST http://localhost:8004/input_bases
Content-Type: application/json

{
    "name": "uav_757",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[
        {
            "type": "WebRTC",
            "source": "main"
        }
    ]
}

### Send towers as JSON
POST http://localhost:8004/input_towers
Content-Type: application/json

{
    "name": "uav_757",
    "category": "dji_M300",
    "ip": "10.42.0.44",
    "camera":[
        {
            "type": "WebRTC",
            "source": "main"
        }
    ]
}

### Send towers empty
POST http://localhost:8004/input_towers
